### ISSUE TITLE
Gamegesign skript (space game)

### ISSUE THREAD

**Issue by desmo9k** [juliusf/krepel#10]
Hallo,

ich hab mal meine Idee als *.pdf hochgeladen damit ihr sie schnelle zerstören könnt. :)
Zu finden im Wiki.

Viel Spaß

**Comment by Manuzor** [comment]
Quick Link: https://github.com/juliusf/krepel/wiki/Game-Design-Ideas#strategy-space-shooter

=> Am Ende vom Strategy Space Shooter.

**Comment by Manuzor** [comment]
Even Quicker Link :D http://data.wohlbrecht.de/emptyspaces_skript.pdf

**Comment by juliusf** [comment]
Hey,
ich finde die Idee hat generell Potential. Allerdings habe ich noch einige Anmerkungen / Fragen. Soll ich das Alles bei Gelegenheit ins Wiki tackern? Oder wollen wir uns nicht lieber am Wochende treffen und das alles noch mal bequatschen?

**Comment by Manuzor** [comment]
Wochenende is eher schlecht für mich, Prüfungszeit und so... Nach dem 8. Februar Hab ich (höchstwahrscheinlich) alles rum. Da kann ich dann vermutlich immer (im Februar zumindest...)

**Comment by juliusf** [comment]
Jop, klingt gut. ich hab grad auch viel zu tun. dann verschieben wir das

**Comment by desmo9k** [comment]
Ein Treffen in den Semesterferien ist wahrscheinlich der beste Startpunkt.
Das es Fragen / Anmerkungen gibt wundert mich nicht, es handelt sich hier schließlich um die unfertige Neuauflage eines nicht ganz beendeten Skripts von vor 3 Jahren.
